cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/K_isMuon_true/ImportantTablesAndFigures/plotJpsiKstFitLogyPretty.pdf kaonmisid.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/Visualize_Weights_KaonMisid_2012.pdf Visualize_Weights_KaonMisid.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/Visualize_Ratios_KaonMisid.pdf Visualize_Ratios_KaonMisid.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/Visualize_Weights_KaonMisid_2012_small.pdf Visualize_Weights_KaonMisid_small.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/Visualize_Ratios_KaonMisid_2012_small.pdf Visualize_Ratios_KaonMisid_small.pdf

cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/Pi_isMuon_true/ImportantTablesAndFigures/plotJpsiKstFitLogyPretty.pdf pionmisid.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/Visualize_Weights_PionMisid_2012.pdf Visualize_Weights_PionMisid.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/Visualize_Ratios_PionMisid.pdf Visualize_Ratios_PionMisid.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/Visualize_Weights_PionMisid_2012_small.pdf Visualize_Weights_PionMisid_small.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta/Visualize_Ratios_PionMisid_small.pdf Visualize_Ratios_PionMisid_small.pdf

