cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/K_isMuon_true/ImportantTablesAndFigures/plotJpsiKstFitLogyPretty.pdf kaonmisid2011.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/Visualize_Weights_KaonMisid_2011.pdf Visualize_Weights_KaonMisid_2011.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/Visualize_Ratios_KaonMisid.pdf Visualize_Ratios_KaonMisid_2011.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/Visualize_Weights_KaonMisid_2011_small.pdf Visualize_Weights_KaonMisid_2011_small.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/Visualize_Ratios_2011_KaonMisid_small.pdf Visualize_Ratios_KaonMisid_2011_small.pdf

cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/Pi_isMuon_true/ImportantTablesAndFigures/plotJpsiKstFitLogyPretty.pdf pionmisid2011.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/Visualize_Weights_PionMisid_2011.pdf Visualize_Weights_PionMisid_2011.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/Visualize_Ratios_PionMisid.pdf Visualize_Ratios_PionMisid_2011.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/Visualize_Weights_PionMisid_2011_small.pdf Visualize_Weights_PionMisid_2011_small.pdf
cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2011/Visualize_Ratios_2011_PionMisid_small.pdf Visualize_Ratios_PionMisid_2011_small.pdf
