scp ss4314@lx00.hep.ph.ic.ac.uk:/vols/lhcb/ss4314/SingleEventSensitivity/SesFUMSB_NOTsimultaneous_final_optimisation_GenLevelEff/plot_interesting/bin/Plot_ALL_Efficiencies_Ratio_Overview_Pretty.pdf .
