scp ss4314@lx00.hep.ph.ic.ac.uk:/home/hep/ss4314/public_html/fitsignal_unblinding/fitsignal_simultaneous_final_genlevelcor_allsyst_upgrade_freeBF_fitatminll/probnnmu035probmu35/workspace_plots/HighFCMEprobnnmu035probmu35plotB23MuNuFitPretty_chi2_simPdfsig_with_0_reallynice.pdf .


scp ss4314@lx00.hep.ph.ic.ac.uk:/home/hep/ss4314/public_html/fitsignal_unblinding/fitsignal_simultaneous_final_genlevelcor_allsyst_upgrade_freeBF_fitatminll/probnnmu035probmu35/workspace_plots/LowFCMEprobnnmu035probmu35plotB23MuNuFitPretty_chi2_simPdfsig_with_0_reallynice.pdf .


scp ss4314@lx00.hep.ph.ic.ac.uk:/home/hep/ss4314/public_html/fitsignal_unblinding/fitsignal_simultaneous_final_genlevelcor_allsyst_upgrade_freeBF_fitatminll/probnnmu035probmu35/workspace_plots/HighFCMEprobnnmu035probmu35plotB23MuNuFitPretty_chi2_simPdfsig_with__1_78461e_08_reallynice.pdf .


scp ss4314@lx00.hep.ph.ic.ac.uk:/home/hep/ss4314/public_html/fitsignal_unblinding/fitsignal_simultaneous_final_genlevelcor_allsyst_upgrade_freeBF_fitatminll/probnnmu035probmu35/workspace_plots/LowFCMEprobnnmu035probmu35plotB23MuNuFitPretty_chi2_simPdfsig_with__1_78461e_08_reallynice.pdf .

