
scp ss4314@lx00.hep.ph.ic.ac.uk:/home/hep/ss4314/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/*thesis*pdf .
scp ss4314@lx00.hep.ph.ic.ac.uk:/home/hep/ss4314/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/*thesis*pdf .

#cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/K_isMuon_true/ImportantTablesAndFigures/plotJpsiKstFitLogyPretty.pdf kaonmisid2016.pdf
#cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/Visualize_Weights_KaonMisid_2016.pdf Visualize_Weights_KaonMisid_2016.pdf
#cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/Visualize_Ratios_KaonMisid.pdf Visualize_Ratios_KaonMisid_2016.pdf
#cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/Visualize_Weights_KaonMisid_2016_small.pdf Visualize_Weights_KaonMisid_2016_small.pdf
#cp ~/public_html/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/Visualize_Ratios_KaonMisid_small.pdf Visualize_Ratios_KaonMisid_2016_small.pdf
#
#cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/Pi_isMuon_true/ImportantTablesAndFigures/plotJpsiKstFitLogyPretty.pdf pionmisid2016.pdf
#cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/Visualize_Weights_PionMisid_2016.pdf Visualize_Weights_PionMisid_2016.pdf
#cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/Visualize_Ratios_PionMisid.pdf Visualize_Ratios_PionMisid_2016.pdf
#cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/Visualize_Weights_PionMisid_2016_small.pdf Visualize_Weights_PionMisid_2016_small.pdf
#cp ~/public_html/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/Visualize_Ratios_PionMisid_small.pdf Visualize_Ratios_PionMisid_2016_small.pdf
