
scp ss4314@lx00.hep.ph.ic.ac.uk:/vols/lhcb/ss4314/fitjpsikst/fitjpsikst_idPION_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/NOFCME/workspace/plotJpsiKstFitLogyPretty_nicecolor.pdf plotJpsiKstFitLogyPretty_nicecolor_2016_KAONMISID.pdf 

scp ss4314@lx00.hep.ph.ic.ac.uk:/vols/lhcb/ss4314/fitjpsikst/fitjpsikst_idKAON_includeswaps_automatize_master_sweight_cinMuonAc_NOghostprob_mydefbin_onnlyONEbinINeta_2016/NOFCME/workspace/plotJpsiKstFitLogyPretty_nicecolor.pdf plotJpsiKstFitLogyPretty_nicecolor_2016_PIONMISID.pdf 
