
scp -r ss4314@lx00.hep.ph.ic.ac.uk:/home/hep/ss4314/public_html/fitsignal/fitsignal_simultaneous_final_GenLevelEff_CorrectMisid_niceplotsincluded/probnnmu035probmu35/workspace_preparation/DataMisid_veryniceplot_paramon_paperHighFCME.pdf misiddatahighfcmeRun1nolog.pdf


scp -r ss4314@lx00.hep.ph.ic.ac.uk:/home/hep/ss4314/public_html/fitsignal/fitsignal_simultaneous_final_GenLevelEff_CorrectMisid_niceplotsincluded/probnnmu035probmu35/workspace_preparation/DataMisid_veryniceplot_paramon_paperLowFCME.pdf misiddatalowfcmeRun1nolog.pdf

scp -r ss4314@lx00.hep.ph.ic.ac.uk:/home/hep/ss4314/public_html/fitsignal/fitsignal_final_GenLevelEff_CorrectMisid_niceplotsincluded/probnnmu035probmu35/workspace_preparation/DataMisid_veryniceplot_paramon_paper.pdf misiddatanofcmeRun1nolog.pdf


